# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c83fedc8f200e054f97f77f13fad8a6a90ed4e10b82150de4036aad1a0dc3c87edaa13ae46ceaaf41da51ead7b77633904258e3ecae1cf39673d45b2588a64ef

test:
  secret_key_base: 3bdcaf07cc0069fb00081d03624cd96c017972ddc01c04765450f4ca091e4c2bcd7a48df39654b83309086f982327cd4d23dc8c2ca060206db586985d6d93efc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
